/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import db.Koneksi;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class PesananTampilFrame extends javax.swing.JFrame {
    private DefaultTableModel model;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PesananTampilFrame.class.getName());

    /**
     * Creates new form PesananTampilFrame
     */
    public PesananTampilFrame() {
        initComponents();
        setTitle("Rekap Pre-Order Album");
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tablePesanan.getModel();
        loadData("");
    }
    
    public void loadData(String keyword) {
        model.setRowCount(0);
        String sql = "SELECT p.id_pesanan, p.nama_pembeli, p.no_hp, a.nama_album, p.jumlah, p.total " +
                     "FROM pesanan p JOIN album a ON p.kode_album = a.kode_album WHERE p.nama_pembeli LIKE ?";
        try (Connection con = Koneksi.getConnection(); 
             PreparedStatement ps = con.prepareStatement(sql)) {
             ps.setString(1, "%" + keyword + "%");
             ResultSet rs = ps.executeQuery();
             while (rs.next()) {
                 model.addRow(new Object[]{
                     rs.getInt("id_pesanan"),
                     rs.getString("nama_pembeli"),
                     rs.getString("no_hp"),
                     rs.getString("nama_album"),
                     rs.getInt("jumlah"),
                     rs.getInt("total")
                 });
             }
        } catch (SQLException ex) {System.err.println(ex.getMessage()); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesanan = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnTambahOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Nama", "No. Telepon", "Pesanan", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablePesanan);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        btnTambahOrder.setText("Tambah Pesanan");
        btnTambahOrder.addActionListener(this::btnTambahOrderActionPerformed);

        jLabel1.setText("Cari");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(this::btnTutupActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        jLabel2.setText("REKAP ORDER GO by HAZEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnTutup))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahOrder)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnUbah)
                    .addComponent(btnTutup)
                    .addComponent(btnHapus))
                .addGap(34, 34, 34))
        );

        txtCari.getAccessibleContext().setAccessibleParent(txtCari);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        loadData(txtCari.getText());
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnTambahOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahOrderActionPerformed
        new PesananTambahFrame(this).setVisible(true);
    }//GEN-LAST:event_btnTambahOrderActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int barisTerpilih = tablePesanan.getSelectedRow();
        if (barisTerpilih == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
            return;
        }
        int idPesanan = Integer.parseInt(tablePesanan.getValueAt(barisTerpilih, 0).toString());
        String namaPembeli = tablePesanan.getValueAt(barisTerpilih, 1).toString();
        
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Hapus pesanan milik " + namaPembeli + "?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_NO_OPTION){
            String sql = "DELETE FROM pesanan WHERE id_pesanan = ?";
            try (Connection con = Koneksi.getConnection();
                    PreparedStatement ps = con.prepareStatement(sql)){
                ps.setInt(1, idPesanan);
                ps.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Pesanan berhasil dihapus!");
                loadData("");
            } catch (SQLException ex){
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus pesanan: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int barisTerpilih = tablePesanan.getSelectedRow();
        if (barisTerpilih == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!");
            return;
        }
        int idPesanan = (int) tablePesanan.getValueAt(barisTerpilih, 0);
        PesananTambahFrame formTambah = new PesananTambahFrame(this);
        formTambah.siapkanDataEdit(idPesanan);
        formTambah.setVisible(true);
    }//GEN-LAST:event_btnUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PesananTampilFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambahOrder;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePesanan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
