/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import db.Koneksi;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class PesananTambahFrame extends javax.swing.JFrame {
    private ArrayList<String> listKodeAlbum = new ArrayList<>();
    private ArrayList<Integer> listHargaAlbum = new ArrayList<>();
    private PesananTampilFrame parent;
    private int idEdit = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PesananTambahFrame.class.getName());

    /**
     * Creates new form PesananTambahFrame
     */
    public PesananTambahFrame(PesananTampilFrame parent) {
        initComponents();
        this.parent = parent;
        setTitle("Input Pesanan PO");
        setLocationRelativeTo(null);
        isiComboBoxAlbum();
    }
    
    private void isiComboBoxAlbum() {
        try (Connection con = Koneksi.getConnection();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM album")) {
            while (rs.next()) {
                cbAlbum.addItem(rs.getString("nama_album") + "(Rp" + rs.getInt("harga") + ")");
                listKodeAlbum.add(rs.getString("kode_album"));
                listHargaAlbum.add(rs.getInt("harga"));
            }
        } catch (SQLException ex) {System.err.println(ex.getMessage());}
    }
    
    public void siapkanDataEdit(int idPesanan){
        this.idEdit = idPesanan;
        setTitle("Ubah Rekap Pesanan PO");
        jLabel5.setText("FORM UBAH ORDER");
        btnSimpanOrder.setText("Simpan Perubahan");
        
        String sql = "SELECT p.nama_pembeli, p.no_hp, p.kode_album, p.jumlah FROM pesanan p WHERE p.id_pesanan = ?";
        try (Connection con = Koneksi.getConnection();
                PreparedStatement ps = con.prepareStatement(sql)){
            ps.setInt(1, idPesanan);
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                txtNama.setText(rs.getString("nama_pembeli"));
                txtHp.setText(rs.getString("no_hp"));
                txtJumlah.setText(String.valueOf(rs.getInt("jumlah")));
                String kodeDb = rs.getString("kode_album");
                int indexAlbum = listKodeAlbum.indexOf(kodeDb);
                if (indexAlbum != -1){
                    cbAlbum.setSelectedIndex(indexAlbum);
                }
            }
        } catch (SQLException ex){
            System.err.println("Gagal memuat data lama: " + ex.getMessage());
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        txtHp = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        cbAlbum = new javax.swing.JComboBox<>();
        btnSimpanOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbAlbum.addActionListener(this::cbAlbumActionPerformed);

        btnSimpanOrder.setText("Submit Order");
        btnSimpanOrder.addActionListener(this::btnSimpanOrderActionPerformed);

        jLabel1.setText("Nama");

        jLabel2.setText("Pesanan");

        jLabel3.setText("No. Telepon");

        jLabel4.setText("Jumlah");

        jLabel5.setText("FORM ORDER");

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(this::btnTutupActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpanOrder)
                        .addGap(18, 18, 18)
                        .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addComponent(cbAlbum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNama)
                    .addComponent(txtJumlah)
                    .addComponent(txtHp, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanOrder)
                    .addComponent(btnTutup))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanOrderActionPerformed
        if (cbAlbum.getSelectedIndex() == -1 || txtJumlah.getText().isEmpty() || txtNama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Form harus terisi!");
            return;
        }
        
        int index = cbAlbum.getSelectedIndex();
        String kodeAlbum = listKodeAlbum.get(index);
        int hargaAlbum = listHargaAlbum.get(index);
        int jmlBeli = Integer.parseInt(txtJumlah.getText());
        int totalBayar = hargaAlbum * jmlBeli;
        
        String sql;
        if (idEdit == -1){
            sql = "INSERT INTO pesanan (nama_pembeli, no_hp, kode_album, jumlah, total) VALUES (?, ?, ?, ?, ?)";
        } else{
            sql = "UPDATE pesanan SET nama_pembeli=?, no_hp=?, kode_album=?, jumlah=?, total=? WHERE id_pesanan=?";
        }
        try (Connection con = Koneksi.getConnection();
            PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, txtNama.getText());
            ps.setString(2, txtHp.getText());
            ps.setString(3, kodeAlbum);
            ps.setInt(4, jmlBeli);
            ps.setInt(5, totalBayar);
            if (idEdit != -1){
                ps.setInt(6, idEdit);
            }
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Pesanan Telah Berhasil!\nTotal: Rp " + totalBayar);
            parent.loadData("");
            dispose();
        } catch (SQLException ex) {JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_btnSimpanOrderActionPerformed

    private void cbAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlbumActionPerformed

    }//GEN-LAST:event_cbAlbumActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanOrder;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cbAlbum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtHp;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}